### ISSUE TITLE
Write Linear Regression prototype

### ISSUE THREAD

**Issue by sakram07** [sakram07/Brainforge#3]

**Comment by tuvtran** [comment]
If no one's taken this, I will

**Comment by sakram07** [comment]
AFAIK no one has taken this (they would have commented the issue).

**Comment by rabiulcste** [comment]
what about polynomial regression?

**Comment by tuvtran** [comment]
I think he meant everything about regression like linear, polynomial, ridge....

**Comment by sakram07** [comment]
Added #11 
We decided on having a totally separate class for each model (for now). I am not sure how much code re-usability will suffer because of that, but we can refactor it later.

So @rabiulcste you can work on polynomial regression while tuvttran works on Linear.

**Comment by divyanshj16** [comment]
This has been completed by me!!
